apiVersion: apps/v1

kind: Deployment

metadata:

  name: jenkins-test

spec:

  selector:

    matchLabels:

      app: jenkins-test

  replicas: 2

  template:

    metadata:

      labels:

        app: jenkins-test

    spec:

      containers:

      - name: jenkins-test

        image: kevin1:5000/jenkins-test

        ports:

        - containerPort: 80